service: media-backend

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-central-1
  memorySize: 256
  versionFunctions: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  nasipoliticiSecrets: ${ssm:/aws/reference/secretsmanager/nasipoliticiSecrets~true}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      MEDIA_TOKEN: ${self:custom.nasipoliticiSecrets.MediaToken}
      MEDIA_URL: ${self:custom.nasipoliticiSecrets.MediaUrl}
