export const partyData = {
  '': 'Všechny',
  čssd: 'ČSSD',
  'strana zelených': 'Strana zelených',
  'kdu-čsl': 'KDU-ČSL',
  ksčm: 'KSČM',
  spd: 'SPD',
  oda: 'Občanská demokratická aliance',
  realisté: 'REALISTÉ',
  ods: 'ODS',
  'věci veřejné': 'Věci veřejné',
  stan: 'STAN',
  'pravý blok': 'Volte Pravý Blok',
  snk: 'SNK Evropští demokraté',
  severočeši: 'Severočeši',
  svobodní: 'Svobodní',
  'česká pirátská strana': 'Česká pirátská strana',
  'top 09': 'TOP 09',
  'strana práv občanů zemanovci': 'Strana Práv Občanů ZEMANOVCI',
  ano: 'ANO',
  'liberálně ekologická strana': 'Liberálně ekologická strana',
  trikolóra: 'Trikolora Svobodní Soukromníci',
  přísaha: 'Přísaha - občanské hnutí Roberta Šlachty',
}

export const functionData = {
  '': 'Všichni',
  poslan: 'poslanec',
  senátor: 'senátor',
  zastupitel: 'zastupitel',
  radní: 'radní',
  místostarost: 'místostarosta',
  starost: 'starosta',
  primátor: 'primátor',
  náměst: 'náměstek',
  hejtman: 'hejtman',
  prezident: 'prezident',
  ministr: 'ministr',
}
